### ISSUE TITLE
0 bins (0 bases in total) formed in MicroPro_ViralPip

### ISSUE THREAD

**Issue by JinqunHuang** [zifanzhu/MicroPro#3]
Dear zifanzhu,

I try to run ViralPip, every step runed fined until  metabat2.

According to the logs, the metabat2 commands runed like this:

metabat2 -i viral_1_vf_filtered_contigs/vf_filtered_contig.fasta -a viral_3_binning/depth.txt -o viral_3_binning/bins_dir/bin -m 1500
MetaBAT 2 (2.14 (Bioconda)) using minContig 1500, minCV 1.0, minCVSum 1.0, maxP 95%, minS 60, and maxEdges 200.
0 bins (0 bases in total) formed.

I also follow the advise from Rob Egan and update the Metabat to version 2.14, but it's also failed.
(https://bitbucket.org/berkeleylab/metabat/issues/79/0-bins-0-bases-in-total-forms)

I recognize the  the virus genome size may be very small and I add the parameter --minClsSize 10000 and find 30 bins.

I'm not sure this is correct. Are there any advises to improve this issue ?

metabat2 -i viral_1_vf_filtered_contigs/vf_filtered_contig.fasta -a viral_3_binning/depth.txt -o viral_3_binning/bins_dir/bin -m 1500 --minClsSize 10000
MetaBAT 2 (2.14 (Bioconda)) using minContig 1500, minCV 1.0, minCVSum 1.0, maxP 95%, minS 60, and maxEdges 200.
30 bins (904305 bases in total) formed.

Thanks again,
Best,
Jinqun Huang

[vf_filtered_contig.fasta.txt](https://github.com/zifanzhu/MicroPro/files/3796548/vf_filtered_contig.fasta.txt)
[depth.txt](https://github.com/zifanzhu/MicroPro/files/3796549/depth.txt)

**Comment by zifanzhu** [comment]
Hi Jinqun,

How many viral contigs were found by VirFinder?

**Comment by JinqunHuang** [comment]
2100 contigs with  Minimum length 1Kbp

![image](https://user-images.githubusercontent.com/47139043/68096285-bbea2f00-feea-11e9-9687-46819880af57.png)

**Comment by zifanzhu** [comment]
Ok! 0 bins formed doesn't mean metabat2 fails. It could mean that the contigs are isolated from each other. The way I handle this is that I treat each contig as one individual bin and calculate abundance profile of them. So you can still find "unknown_viral_abundance.csv" in res/ folder, right? I didn't manipulate the parameters of metabat2; thus can't comment on that. Hope this helps.

**Comment by JinqunHuang** [comment]
Thanks, zifan.

unfortunately, I can't find res/unknown_viral_abundance.csv.

It got error with "R --no-save --file=scripts/u_v_abund.R &> logs/viral_3_binning/u_v_abund.log". 
Because the “viral_3_binning/bins_dir/bin” was empty from the  metabat2 by default parameters in ViralPip.
[log.tar.gz](https://github.com/zifanzhu/MicroPro/files/3822835/log.tar.gz)
[ViralPip.sh.log.txt](https://github.com/zifanzhu/MicroPro/files/3822836/ViralPip.sh.log.txt)

**Comment by zifanzhu** [comment]
Hi Jinqun,

Could you please send me the 'snake-binning-P' file you used? It should locate under folder 'ViralPip'. Seems there's some problem therein.

Best,
Zifan

**Comment by JinqunHuang** [comment]
[snake-binning-P.txt](https://github.com/zifanzhu/MicroPro/files/3959307/snake-binning-P.txt)
Dear zifan, sorry for the delay.
The  'snake-binning-P' has shown as above.
Thank you for your help.

Best，
Jinqun Huang

**Comment by zifanzhu** [comment]
Hi Jinqun,

It appears that you weren't using the latest MicroPro. Updating it (by replacing all the 'snake-*' files with the new ones) should solve your problem.

Best,
Zifan

**Comment by JinqunHuang** [comment]
Thanks a lot !!
The last version of ViralPip runs successfully.

Best,
Jinqun Huang
